<?php
// Include connection
if (isset($_SESSION['success_message'])) {
    echo '<div class="alert alert-success">' . $_SESSION['success_message'] . '</div>';
    unset($_SESSION['success_message']);
}
if (isset($_SESSION['error_message'])) {
    echo '<div class="alert alert-danger">' . $_SESSION['error_message'] . '</div>';
    unset($_SESSION['error_message']);
}

// Check if user is logged in and 2FA verified
if (!isset($_SESSION['logged_in']) || $_SESSION['logged_in'] !== true || 
    !isset($_SESSION['2fa_verified']) || $_SESSION['2fa_verified'] !== true) {
    header('Location: index.php');
    exit();
}
// Include connection
include '../connection.php';

// Check if connection is successful
if (!$db) {
    die("Database connection failed: " . mysqli_connect_error());
}

// Function to perform database backup
function backupDatabase($db) {
    // Get all table names
    $tables = array();
    $result = $db->query("SHOW TABLES");
    while ($row = $result->fetch_row()) {
        $tables[] = $row[0];
    }
    
    // Create backup directory if it doesn't exist
    $backup_dir = '../backups/';
    if (!file_exists($backup_dir)) {
        mkdir($backup_dir, 0755, true);
    }
    
    // Create backup file with timestamp
    $backup_file = $backup_dir . 'backup_' . date('Y-m-d_H-i-s') . '.sql';
    
    // Open file for writing
    $handle = fopen($backup_file, 'w');
    
    // Add header information
    fwrite($handle, "-- Database Backup: " . date('Y-m-d H:i:s') . "\n");
    fwrite($handle, "-- Generated by RFIDGPMS System\n\n");
    
    // Process each table
    foreach ($tables as $table) {
        fwrite($handle, "-- Table structure for table `$table`\n");
        fwrite($handle, "DROP TABLE IF EXISTS `$table`;\n\n");
        
        // Get table structure
        $result = $db->query("SHOW CREATE TABLE `$table`");
        $row = $result->fetch_row();
        fwrite($handle, $row[1] . ";\n\n");
        
        // Get table data
        $result = $db->query("SELECT * FROM `$table`");
        $num_fields = $result->field_count;
        
        fwrite($handle, "-- Dumping data for table `$table`\n");
        
        while ($row = $result->fetch_row()) {
            fwrite($handle, "INSERT INTO `$table` VALUES (");
            
            for ($j = 0; $j < $num_fields; $j++) {
                $row[$j] = addslashes($row[$j]);
                $row[$j] = str_replace("\n", "\\n", $row[$j]);
                
                if (isset($row[$j])) {
                    fwrite($handle, '"' . $row[$j] . '"');
                } else {
                    fwrite($handle, '""');
                }
                
                if ($j < ($num_fields - 1)) {
                    fwrite($handle, ',');
                }
            }
            
            fwrite($handle, ");\n");
        }
        
        fwrite($handle, "\n\n");
    }
    
    fclose($handle);
    
    // Return backup file info
    return [
        'success' => true,
        'file' => basename($backup_file),
        'size' => formatBytes(filesize($backup_file)),
        'time' => date('Y-m-d H:i:s')
    ];
}

// Function to format bytes
function formatBytes($size, $precision = 2) {
    $base = log($size, 1024);
    $suffixes = array('', 'KB', 'MB', 'GB', 'TB');
    
    return round(pow(1024, $base - floor($base)), $precision) . ' ' . $suffixes[floor($base)];
}

// Check if this is an AJAX request
if (isset($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest') {
    // Perform backup
    $backup_result = backupDatabase($db);
    
    // Return JSON response
    header('Content-Type: application/json');
    echo json_encode($backup_result);
    exit;
}

// If not AJAX, redirect back to dashboard
header('Location: dashboard.php');
exit;
?>